language: ruby
rvm:
- 2.3.1
cache: bundler
deploy:
  provider: heroku
  api_key:
    secure: Vhvs+Y7M4ypVXcUVVQrmBohtvcq248Z3s5nvLw2yWvt5rG06PUMj8F2Kr7gWAx7RK3ue42Up9keMR+ZjEw0RhxCo4+Spqh5irLpN5sdJerrZCTF9BtTLDqWyGqwqb4G3E1zWrSwptp12SROqy8a2pTmw5/zz9/l40bHmP0M/i5IyGqXD8/IPBerV4sYH8bw+9QTgSZJUD5J02I62iM0UKN+IEWhUYCvq8zjGea4KKYB2dUQhHHYnCawEd9Y37uVWppfVp+AWY9IrztNkJdCia55euXohMXch3+cLNwAbDE8LcewCP9ECpZgBj8MlfIp09DcM9FUQgsTO+SMyIBCvUTTVv07LQ2JyeT6OE8TK4OtU7wI8u4MXHUGgjHCIh7yIjKS93Uc/LJBefXGv/wEF/VwaHHkkD0TfsGLq9LI5zpin9EN3mduhAsvYBtE/R0BHqOHoxTuWleXUzrGX7FBwyv2BhOQZZsGYnru//aeUYqnpHn1P6vUDmFVdBFrBVQiqb6smlmtEnVYOjaIxsava+tFhuEDwPiRl1VZzTTH4ljH8NaBse4/erAKT64yuA+WheqEnssI6n0nJecMr1OM4HY6M7SJtmmGXb1M3ei9d4XFUNZ9hwfVvSe9C7w6T3FW8p5VUXI8Jk22CpUnBIFhsuA9Fy2/u+G79epOsoRm0fcQ=
  app: asp-league-staging
  on: staging
  run: "rake db:migrate"
script: bundle exec rails db:migrate && bundle exec rake
bundler_args: --without development
branches:
  only:
  - staging
