version: '2'
services:
  redis:
    image: redis
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - ./dump.rdb:/dump.rdb
    command: redis-server /usr/local/etc/redis/redis.conf
    expose:
      - 6379
  database:
    image: postgres
    expose:
      - 5432
    volumes_from:
      - vc_database
  vc_database:
    image: postgres
    volumes:
      - /var/lib/postgresql/data
    command: echo "Started volume container"
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      API_KEY:
      REDIS_URL: redis://redis
      DATBASE_URL: postgres://postgres:5432
    links:
      - redis
      - database
